### ISSUE TITLE
Role triggers .user.ini integrity check with nextcloud 13.0.4

### ISSUE THREAD

**Issue by lalmeras** [rbicker/ansible-nextcloud#10]
In nextcloud 13.0.4, max_input_time and max_execution_time configuration are dropped from .user.ini. As Nextcloud checks .user.ini consistency by copying installed file, setting default values on copied file, then computing file checksum (described here: https://github.com/nextcloud/server/issues/115).

As the ``.user.ini`` deployed by the role contains this configuration items, integrity check now fails, with a warning in administration pages (see screen capture). This does not prevent nextcloud to work.

The better way I see to fix it is to template .user.ini to drop problematic section, based on ``ansible_version`` variable.

Do you see / plan any other fix ? Interested by a PR for this ?

![nextcloud-integrity](https://user-images.githubusercontent.com/1030469/41497830-f15a8142-715d-11e8-97eb-14bd7e83f3a8.png)

**Comment by rbicker** [comment]
Hi, thanks for your message. I am already working on a fix using lineinfile with backrefs=yes instead of a template. This way, the line will only be modified if it already exists. I need to do some more testing but I will probably push the change by the end of this week. BR

**Comment by rbicker** [comment]
I just pushed my fix. During my tests, I saw that max_execution_time and max_input_time were also missing in older versions of nextcloud. Not sure why the consistency check used to succeed.

I ended up putting these options in /etc/php.ini

**Comment by lalmeras** [comment]
I think this bug was revealed by my last PR, as code integrity check is performed by update/setup scripts. As my PR fixed the fact that during upgrade, nextcloud original ``.user.ini`` was not modified with custom settings, no integrity violation were detected.

Thanks for your quick fix.
