### ISSUE TITLE
Wrong URL in Activity notifications

### ISSUE THREAD

**Issue by lalmeras** [rbicker/ansible-nextcloud#11]
Hi,

I step into a problem with the URL pushed in Activity notifications. URL is **http://localhost**.

From a Nextcloud viewpoint, I find out it is related to the value of **overwrite.cli.url**. From my installation, value is http://localhost (``sudo -u nginx php /opt/nextcloud/web/occ config:system:get overwrite.cli.url``).

Not sure of the way we should fix this. The better option from my point of view should be to introduce a ``nextcloud_overwrite_cli_url: "{{ ('https://' if nextcloud_use_https else 'http://') + nextcloud_domain }}". 
Then to use it in installation.yml to set **overwrite.cli.url**.

This solution provides a decent default behavior.

I'm not sure of the behavior of upgrade process, as it appears that occ system:config:set is done only during installation ? Is config.php preserved by updater.phar during update process ? If this is the case, existing installation needs to be fixed manually (fine for me).

I can work on a pull-request implementing this solution, or any solution you prefer.

**Comment by rbicker** [comment]
Hi

I am not to sure what the default for this option should be, it really depends on the situation. We have installations behind a reverse proxy where your suggestion would not work.

I introduced a new parameter called nextcloud_config_options which can be used to set custom options in config.php:
```yaml
nextcloud_config_options: # additional options to set in config.php
 - { option: overwrite.cli.url, value: "'https://nextcloud.mydomain.com'" }
```

Maybe this fits your needs?

BR

**Comment by lalmeras** [comment]
Nice proposal. I'll try this option.

**Comment by lalmeras** [comment]
Hi, I think I already replied to this issue.

I try your proposal and it fulfills my needs. Closing issue.
