### ISSUE TITLE
Update PHP packages to version 7.2

### ISSUE THREAD

**Issue by hlovdal** [rbicker/ansible-nextcloud#15]
This role currently uses [php 7.1 packages](https://webtatic.com/packages/php71/). There are [7.2 packages](https://webtatic.com/packages/php72/) available and most notably they have dropped the `php71w-mcrypt` package out of [security concerns](https://webtatic.com/packages/php72/#mcrypt-no-longer-provided) so I think it would be a good idea to update. As far as I understand there are currently no known vulnerabilities with the mcrypt package, but better safe than sorry.

**Comment by rbicker** [comment]
Hi
I need to look into this. I tried to update to php 7.2 a long time ago but there where some issues with the current nextcloud version back then. I will try again whenever I find the time.
Thanks

**Comment by Netbulae** [comment]
Nextcloud 15 has php 7.2 as default: 

https://docs.nextcloud.com/server/15/admin_manual/installation/php_72_installation.html

**Comment by rbicker** [comment]
This has been changed in the latest versions of rbicker.nextcloud
