### ISSUE TITLE
Inconsistencies about nextcloud_web_root

### ISSUE THREAD

**Issue by lalmeras** [rbicker/ansible-nextcloud#3]
If nextcloud_web_root does not end by /nextcloud, installation script fails as:

* archive is extracted in {{ nextcloud_web_root }}/..
* archive root dir is ``nextcloud``
* so if ``nextcloud_web_root`` last part is not nextcloud, path are not consistent

I suggest to use unarchive option: ``extra_opts: --strip-components=1`` and to get rid of ``/..`` in ``dest``, so that it is the content of archive's nextcloud folder that is placed directly in ``nextcloud_web_root``.

This solution is backward compatible, and allow to use arbitrary ``nextcloud_web_root``. I can provide a PR if you agree with it.

Else, documentation must be updated.

**Comment by rbicker** [comment]
good catch! I implemented your suggestions and did a quick installation, it seems to be working. Would you mind doing a quick test on your side? If everything works, I will import it to ansible galaxy. Thanks

**Comment by lalmeras** [comment]
Successfully tested here with ca86ea407869e7ba290ffe8910444d23f436f6dc ; thanks for this quick fix.

With the two last fixes you merge, role is fully functional in my environment.

A last question: on my side, I never needed to use ``--show-transformed-names`` with ``--strip-components``, and it never failed, so I'm not sure it is needed here or if it could trigger bugs. Are you sure it is needed ?

**Comment by lalmeras** [comment]
Make a mistake, misconfigured galaxy src ; I test with own branch and my own fix. I just see it as I encounter the ugrade typo that breaks the role.

I'll test again later with a clean environment.

**Comment by lalmeras** [comment]
I just check on a clean docker environment and it works fine.

Still interested about your point of view on ``show-stored-names`` (wrongly written show-transformed-names in my previous message).

**Comment by rbicker** [comment]
It seems that the show-stored-names option was necessary in some older versions of ansible (https://github.com/ansible/ansible-modules-core/issues/2480)

**Comment by lalmeras** [comment]
Thanks for the insight, and for the fix.
