### ISSUE TITLE
Redis server config causes Nextcould to not work

### ISSUE THREAD

**Issue by flo-rian** [rbicker/ansible-nextcloud#33]
I've installed NC 20.0.1.1 on CentOS 8.2 via this playbook.
When I try to open my NC mainpage i get an error (sorry in german):

```
Interner Serverfehler

Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.
Technische Details

    Entfernte Adresse: <snipped>
    Anfragekennung: <snipped>
```
After commenting out the redis part in the config.php of nextcloud things work. I have no experience with redis but for me this looks like it is a problem with the redis install/configuration. I don't know what other information would be helpfull but I'll include if I am told what would help.

**Comment by flo-rian** [comment]
Some more details from the nginx error logfile:
`[error] 1002#0: *2 FastCGI sent in stderr: "PHP message: {"reqId":"GWNmiTC8OHxJ3RwlHief","level":3,"time":"2020-11-09T20:21:00+00:00","remoteAddr":"192.168.102.65","user":"--","app":"index","method":"GET","url":"/js/core/merged-template-prepend.js?v=52518fd7-0","message":{"Exception":"RedisException","Message":"Permission denied","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/RedisFactory.php","line":92,"function":"connect","class":"Redis","type":"->","args":["/var/run/redis/redis.sock","0",0]},{"file":"/var/www/nextcloud/lib/private/RedisFactory.php","line":108,"function":"create","class":"OC\\RedisFactory","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Memcache/Redis.php","line":43,"function":"getInstance","class":"OC\\RedisFactory","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Memcache/Factory.php","line":135,"function":"__construct","class":"OC\\Memcache\\Redis","type":"->","args":["eb995fc23f7a98a7df76042c350876fb/lock"]},{"file":"/var/www/nextcloud/lib/private/Server.php","line":1023,"functi...PHP message: {"reqId":"GWNmiTC8OHxJ3RwlHief","level":3,"time":"2020-11-09T20:21:00+00:00","remoteAddr":"192.168.102.65","user":"--","app":"no app in context","method":"GET","url":"/js/core/merged-template-prepend.js?v=52518fd7-0","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve trashManager! Class trashManager does not exist","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["trashManager"]},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":156,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["trashManager",true]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":430,"function":"query","class":"OC\\ServerContainer","type":"->","args":["trashManager",true]},{
`

**Comment by rbicker** [comment]
Hi

Thanks for raising this issue.

Quick question, did you download the role from this github repository or did you install it from ansible galaxy? I made some updates for CentOS 8.2 yesterday and I was able to run a test installation. As I imported the role to ansible galaxy today, the role on ansible galaxy was not up to date.

If it still does not work with the most recent version of the role, could you please check if selinux is enabled and also what the permissions of the redis socket are?
```bash
getenforce
ls -lZ /var/run/redis
```

Thanks

BTW: don't worry about the German, I am actually Swiss so this is not an issue for me ;-)

**Comment by flo-rian** [comment]
Hi! I've downloaded from galaxy: `ls -l` says `Nov  5 01:04 rbicker.nextcloud`
It is a bit inconvenient for me to run it again as I used the role to install an nextclound instance I want to use for myself and after that I ran a few hardening scripts that changed (a few too many) things (which I had to partly take back). But i could look at the changes in git and maybe it becomes apparent what I'd have to change. 
Otherwise I could run your script against my vagrant CentOS 8 test box, but I guess I have tested it with something similar?

SELinux is on enforcing (one of the reasons why I chose CentOS for that internet-facing server-li).
`ls -lZ` says `srwxrwx---. 1 redis redis system_u:object_r:redis_var_run_t:s0 0 Nov 10 23:55 redis.sock`

Maybe as an feature idea: would it be possible to add an option to the role to not install/use redis at all? I removed it in the config now but just did not yet uninstall redis yet. As I use a rather small machine to run nextcloud for only a very small number of users it might not be needed.
After I was trying to find a solution for redis yesterday I realized security could be slightly improved if you'd configure redis to not listen on a network port at all (as you use the socket anyway): less exposure.

Cheers,
Flo

**Comment by rbicker** [comment]
Hi Flo

Thanks for your feedback. 

Basically what we are trying to do is to install nextcloud following some common and our own best practices and using redis is actually one of them. So this won't be something that we personally will invest our time in but we are open for pull requests regarding that matter.

So the file permission seem correct, could you please check one more thing?
```bash
# check if httpd_can_network_connect se bool is on:
getsebool httpd_can_network_connect

# if it is off, change it:
setsebool -P httpd_can_network_connect_db on
```

Thanks

**Comment by flo-rian** [comment]
Hi Raphael

I ran the test: `getsebool httpd_can_network_connect` results in
`httpd_can_network_connect --> on`

I understand your reasoning about not putting extra effort into a feature you won't use. 

Concerning the redis issue I don't know how to help because I never used redis. Just read the config file.

Best regards,
Flo

**Comment by flo-rian** [comment]
One more item I've checked (inspired by your late suggestion): I read https://www.nginx.com/blog/using-nginx-plus-with-selinux/
and ran `grep nginx /var/log/audit/audit.log | audit2why` but this did not bring up any issues.

**Comment by rbicker** [comment]
Hmm this is weird. Could you please do a quick check with selinux temporarily disabled? `setenforce 0`

**Comment by flo-rian** [comment]
I tried temporarily disabling and it did not help.
Just to make sure that I did not change too much here is the relevant part of the config:
```
'memcache.local' => '\OC\Memcache\APCu',
  'redis' =>  [
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => '0',
  ),
  ],
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'logfile' => '/var/log/nextcloud/nextcloud.log',
```
If I comment out the `memcache.locking` line things work. If I don't things fail. 
I've tried with `\\` and `\` and it does not seem to make a difference as I saw both versions in online docs.
But I've change my other config quite a bit (moved nextcloud to a subdirectory of the web root and other stuff) so I am not sure whether I work on a clean install and everything I do is exactly as it would appear with your current version of the playbook.
I don't want to keep you too busy with debugging that issue if it might me a quirk of my installation. I might test it on a clean vagrant version of CentOS 8.2 when I got some time for that.

Regarding caching I noticed something else: I think the PHP package (of the non-system PHP version repo) for the APCu did not get installed. So I installed it myself. But as I am a total PHP noob I don't know how to check the effect of that. But maybe you can check whether that package needs to be installed by the playbook.

**Comment by rbicker** [comment]
Yes the file level permissions seem to be correct and if disabling selinux does not make it work, it is kind of hard to debug for me because the issue might be specific to your installation.
The apcu package does not get installed by choice because if redis works the package is not needed. But of course manually installing it works fine.

So I will close the ticket for now, but if you experience similar issues in a fresh (test) install feel free to open up a new ticket!
