### ISSUE TITLE
letsencrypt support?

### ISSUE THREAD

**Issue by ralvaradof** [rbicker/ansible-nextcloud#9]
Hi,

I'm working with this role, and add letsencrypt support to the role will be great.

Thanks for your work

Regards

**Comment by rbicker** [comment]
Hi

Thanks for your suggestion! We have though about adding letsencrypt support but we decided against it (at least for know). Some thoughts:

- There are multiple ansible roles to implement let's encrypt certificates, so one of these roles can be combined with the rbicker.nextcloud role
- There are many different szenarios how ssl can be implemented, we normally buy certs or use reverse proxies with ssl termination in front of our instances. We don't want to overload the role with to much "side-work", the self-signed certificate is just to get you started.

I am closing this for now, but if more people keep asking for this, we might reconsider.

Thanks & Best Regards
